micronaut:
  application:
    name: userService
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:mysql://localhost:3306/user-db
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL
#    driverClassName: com.mysql.cj.jdbc.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
